DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
    id SERIAL PRIMARY KEY NOT NULL,
    email VARCHAR(30) NOT NULL UNIQUE,
    password VARCHAR(90) NOT NULL,
    username VARCHAR(30) NOT NULL UNIQUE
);

